from .login_view import LoginWindow
from .dashboard_view import DashboardView
from .kapal_view import KelolaDKapalView
from .jadwal_view import KelolaJadwalView
from .reservasi_view import ReservasiView
from .laporan_view import LaporanManifesView
from .user_view import ManajemenUserView
from .rute_view import KelolaRuteView
from .cari_tiket_view import CariTiketView
from .about_view import AboutView
